import { Container, Heading, Wrap, WrapItem } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import PaymentLinkCard from "../components/PaymentLinkCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main>
        <Container maxW='' centerContent={true}>
          <Heading as='h3' size='lg' marginBottom='32px'>
            Your payment links
          </Heading>
          <Wrap spacing={24} shouldWrapChildren={true} align='center'>
            <PaymentLinkCard
              link="pay.solfront.app/JFOG"
              productName="Chair"
              price="39"
              currency="USD"
            />
            <PaymentLinkCard
              link="pay.solfront.app/JFOG"
              productName="Chair"
              price="39"
              currency="USD"
            />
            <PaymentLinkCard
              link="pay.solfront.app/JFOG"
              productName="Chair"
              price="39"
              currency="USD"
            />
            <PaymentLinkCard
              link="pay.solfront.app/JFOG"
              productName="Chair"
              price="39"
              currency="USD"
            />
          </Wrap>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
